name: judiciousjunkie
favicon: null
layout_spectrum: 0.3973924007732421
typography_spectrum: 0.11811075056903064
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5069140617270023
  lightness: 0.6600294907111675
  saturation: 0.2806032409425825
  rhythmicContrast: 0.2890975659247488
purpose: []
